#include "sem.h"
#include "threads.h"

struct TCB_t *runQ = NULL; 
struct semaphore *full = NULL, *empty = NULL, *mutex = NULL;

int b=0,p=0,c=0,n=0;   
int in=0, out = 0;    
int *buffer = NULL;


void producer(int threadid){
	int count = 0;
	int i=0;
	while(i<n){      
		P(empty,threadid);
		P(mutex,threadid);
		buffer[in] = threadid;
		in = (in+1) % b;
		count++;
		//fprintf(fp,"\n Producer %d is producing item number %d \n", threadid,count);
		printf("\n Producer %d is producing item number %d \n", threadid,count);
		V(mutex);
		V(full);
		i++;   
		yield();
	}
	if (runQ == NULL){
		exit(1);   
	}
	TCB_t *pdel = DelQueue(&runQ);
	swapcontext(&(pdel->context),&(runQ->context));
}

void consumer(int threadid){	
	int i=0;
	while(i<n){       
		P(full,threadid);
		P(mutex,threadid);
		//fprintf(fp,"\n Consumer %d is consuming item generated by Producer %d\n",-1*threadid,buffer[out]);
		printf("\n Consumer %d is consuming item generated by Producer %d \n",threadid*-1,buffer[out]);
		buffer[out] = -1;
		out = (out+1) % b;
		V(mutex);
		V(empty);
		i++;
		yield();
	}
	if (runQ == NULL){
		exit(1);
	}
	TCB_t *cdel = DelQueue(&runQ);
	swapcontext(&(cdel->context),&(runQ->context));
}
                
int main(int argc, char *argv[]) {    
	char comma;
	scanf("%d%c%d%c%d%c%d",&b,&comma,&p,&comma,&c,&comma,&n);
	runQ = NewItem();
	full = (struct semaphore*) malloc(sizeof( struct semaphore));
	empty = (struct semaphore*) malloc(sizeof(struct semaphore));  
	mutex = (struct semaphore*) malloc(sizeof(struct semaphore));
	InitQueue(&runQ);
	IntiSem(empty,b);
	IntiSem(full,0);   
	IntiSem(mutex,1);

	buffer = (int *)malloc(sizeof((int) b));   
	for (int i=0; i< p+c; i++){
		int threads=0;   
		scanf("%d",&threads);  
		if (threads >=0){  
			start_thread(*producer,threads);
		}
		else{
			start_thread(*consumer,threads);
		}
	}
	run();
}